name = "greta"
defaultTargets = ["Greta", "greta"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "Greta"

[[lean_exe]]
name = "greta"
root = "Main"
supportInterpreter = true
