/-
Context-free grammars, parse trees and ambiguity (Definitions A.1–A.3), the translation
of a CFG into a tree automaton (Definition A.9), and its correctness (Theorem A.10).
-/
import Greta.Semantics

namespace Greta

/-- Nonterminal symbols.  Strings, as in `lib/cfg.ml`. -/
abbrev Nonterminal := String

/-- An element of the right-hand side of a production: `Cfg.sigma` of the reference. -/
inductive SigmaElt where
  | term : Terminal → SigmaElt
  | nt   : Nonterminal → SigmaElt
deriving DecidableEq, Repr, Inhabited

/-- A production `A → β`. -/
abbrev Production := Nonterminal × List SigmaElt

/-- A context-free grammar `(V, Σ, S, P)` (Definition A.1).

The reference implementation carries a *list* of start nonterminals, so we do too; the
paper's single start symbol is the singleton case. -/
structure CFG where
  nonterms : List Nonterminal
  terms    : List Terminal
  starts   : List Nonterminal
  prods    : List Production
deriving Repr, Inhabited, DecidableEq

namespace CFG

/--
Display name of a production's ranked symbol: the first terminal of its right-hand side.

The paper writes `δ` when the right-hand side contains no terminal; the reference
implementation (`Cfg.first_terminal_of`) uses the empty string, and we follow the latter
so that symbol names generated here agree with those generated by the OCaml tool.  The
name plays no semantic role: symbols are told apart by their production identifier.
-/
def firstTermName (rhs : List SigmaElt) : String :=
  (rhs.findSome? fun
    | .term a => some a
    | .nt _   => none).getD ""

/-- The ranked symbol of the `i`-th production (Definition A.4). -/
def symOf (i : Nat) (p : Production) : Sym :=
  ⟨(i : Int), firstTermName p.2, p.2.length⟩

theorem symOf_ne_epsSym (i : Nat) (p : Production) : symOf i p ≠ epsSym := by
  intro h
  have hid : ((i : Int)) = (-1 : Int) := congrArg Sym.id h
  omega

/-- Productions paired with their ranked symbols, in grammar order. -/
def rankedProds (g : CFG) : List (Sym × Production) :=
  g.prods.zipIdx.map fun pi => (symOf pi.2 pi.1, pi.1)

theorem rankedProds_sym_ne_eps {g : CFG} {sp : Sym × Production} (h : sp ∈ g.rankedProds) :
    sp.1 ≠ epsSym := by
  simp only [rankedProds, List.mem_map] at h
  obtain ⟨⟨p, i⟩, _, rfl⟩ := h
  exact symOf_ne_epsSym i p

/-- `Prod` of Definition A.9: the production a ranked symbol came from. -/
def prodOfSym (g : CFG) (f : Sym) : Option Production :=
  (g.rankedProds.find? fun sp => sp.1 = f).map Prod.snd

/-- Right-hand-side elements become transition right-hand-side entries. -/
def betaOf : SigmaElt → Beta Nonterminal
  | .term a => .term a
  | .nt A   => .state A

/--
Translation of a CFG into a tree automaton (Definition A.9): states are nonterminals,
final states are the start nonterminals, and each production becomes one transition.
-/
def toTA (g : CFG) : TA Nonterminal where
  states    := g.nonterms
  alphabet  := g.rankedProds.map Prod.fst
  terminals := g.terms
  finals    := g.starts
  trans     := g.rankedProds.map fun sp => ⟨sp.2.1, sp.1, sp.2.2.map betaOf⟩

/-! ### Parse trees -/

mutual

/--
`g.isParseTreeOf A t` decides whether `t` is a parse tree of `g` rooted at `A`
(Definition A.2), in the ranked-symbol encoding: an internal node labelled `f` must come
from a production of `A` whose right-hand side is matched by the node's children.
-/
def isParseTreeOf (g : CFG) (nt : Nonterminal) : Tree → Bool
  | .leaf _ => false
  | .node f ts =>
      g.rankedProds.any fun sp =>
        decide (sp.1 = f) && decide (sp.2.1 = nt) && matchRhs g ts sp.2.2
  termination_by t => sizeOf t

/-- Children of a node matched against the right-hand side of a production. -/
def matchRhs (g : CFG) : List Tree → List SigmaElt → Bool
  | [],      []            => true
  | t :: ts, .term a :: rs => isLeafOf t a && matchRhs g ts rs
  | t :: ts, .nt B :: rs   => isParseTreeOf g B t && matchRhs g ts rs
  | _,       _             => false
  termination_by ts _ => sizeOf ts

end

/-- Complete parse trees of `g`: `L_G` of Definition A.2. -/
def isParseTree (g : CFG) (t : Tree) : Bool :=
  g.starts.any fun s => g.isParseTreeOf s t

/-- A grammar is ambiguous when two distinct parse trees share a yield (Definition A.3). -/
def Ambiguous (g : CFG) : Prop :=
  ∃ t₁ t₂ : Tree, g.isParseTree t₁ ∧ g.isParseTree t₂ ∧ t₁ ≠ t₂ ∧ t₁.yield = t₂.yield

/-! ### Correctness of the translation (Theorem A.10) -/

/-- The translation introduces no ε-transitions, so its ε-closure is the identity. -/
def idTable : EpsTable Nonterminal := fun q => [q]

theorem toTA_no_eps (g : CFG) : (g.toTA).epsEdges = [] := by
  simp only [TA.epsEdges, toTA, List.filterMap_map, List.filterMap_eq_nil_iff]
  intro sp hmem
  simp only [Function.comp_apply]
  rw [if_neg (rankedProds_sym_ne_eps hmem)]

theorem isEpsClosure_idTable (g : CFG) : IsEpsClosure g.toTA idTable := by
  intro q p
  simp only [idTable, List.mem_singleton]
  refine ⟨fun h => h ▸ .refl _, fun h => ?_⟩
  cases h with
  | refl => rfl
  | step he _ => rw [toTA_no_eps] at he; simp at he

theorem any_singleton_mem {α : Type} [DecidableEq α] (q : α) (l : List α) :
    (l.any fun r => decide (q ∈ [r])) = decide (q ∈ l) := by
  induction l with
  | nil => simp
  | cons x xs ih =>
      rw [List.any_cons, ih, Bool.eq_iff_iff]
      simp only [Bool.or_eq_true, decide_eq_true_eq, List.mem_singleton, List.mem_cons]
      tauto

theorem any_idTable_mem (q : Nonterminal) (l : List Nonterminal) :
    (l.any fun r => decide (q ∈ idTable r)) = decide (q ∈ l) := any_singleton_mem q l

theorem toTA_trans (g : CFG) :
    (g.toTA).trans = g.rankedProds.map fun sp => ⟨sp.2.1, sp.1, sp.2.2.map betaOf⟩ := rfl

theorem toTA_realTrans (g : CFG) :
    (g.toTA).realTrans = g.rankedProds.map fun sp => ⟨sp.2.1, sp.1, sp.2.2.map betaOf⟩ := by
  rw [TA.realTrans, toTA_trans, List.filter_eq_self.mpr]
  intro tr htr
  simp only [List.mem_map] at htr
  obtain ⟨sp, hsp, rfl⟩ := htr
  simpa using rankedProds_sym_ne_eps hsp

/--
Children matching in `g.toTA` agrees with right-hand-side matching in `g`, given the
statement of Theorem A.10 for each child.
-/
theorem matchAll_eq_matchRhs (g : CFG) :
    ∀ (ts : List Tree),
      (∀ t ∈ ts, ∀ q, q ∈ (g.toTA).evalT idTable t ↔ g.isParseTreeOf q t = true) →
      ∀ rs : List SigmaElt, (g.toTA).matchAll idTable ts (rs.map betaOf) = g.matchRhs ts rs := by
  intro ts
  induction ts with
  | nil =>
      intro _ rs
      cases rs with
      | nil => simp [TA.matchAll, matchRhs]
      | cons r rs => cases r <;> simp [TA.matchAll, matchRhs, betaOf]
  | cons t ts ih =>
      intro hts rs
      have hhd := hts t (List.mem_cons_self ..)
      have htl : ∀ u ∈ ts, ∀ q, q ∈ (g.toTA).evalT idTable u ↔ g.isParseTreeOf q u = true :=
        fun u hu => hts u (List.mem_cons_of_mem _ hu)
      cases rs with
      | nil => simp [TA.matchAll, matchRhs]
      | cons r rs =>
          cases r with
          | term a =>
              simp only [List.map_cons, betaOf, TA.matchAll, matchRhs, ih htl rs]
          | nt B =>
              have hdec : decide (B ∈ (g.toTA).evalT idTable t) = g.isParseTreeOf B t := by
                cases hb : g.isParseTreeOf B t <;> simp [hhd B, hb]
              simp only [List.map_cons, betaOf, TA.matchAll, matchRhs, ih htl rs,
                any_idTable_mem, hdec]

/-- **Theorem A.10** (pointwise form): `A_G` assigns exactly the parse-tree nonterminals. -/
theorem mem_evalT_iff (g : CFG) :
    ∀ (t : Tree) (q : Nonterminal),
      q ∈ (g.toTA).evalT idTable t ↔ g.isParseTreeOf q t = true := by
  intro t
  induction t using Tree.rec' with
  | hleaf a => intro q; simp [TA.evalT, isParseTreeOf]
  | hnode f ts ih =>
      have hkey := matchAll_eq_matchRhs g ts ih
      intro q
      simp only [TA.evalT, isParseTreeOf, toTA_realTrans, List.filterMap_map, List.mem_filterMap,
        List.any_eq_true, Bool.and_eq_true, decide_eq_true_eq, Function.comp_apply]
      constructor
      · rintro ⟨sp, hmem, hif⟩
        split at hif
        · next hc =>
            simp only [Option.some.injEq] at hif
            exact ⟨sp, hmem, ⟨hc.1, hif⟩, by rw [← hkey sp.2.2]; exact hc.2⟩
        · simp at hif
      · rintro ⟨sp, hmem, ⟨hf, hq⟩, hm⟩
        refine ⟨sp, hmem, ?_⟩
        rw [if_pos ⟨hf, by rw [hkey sp.2.2]; exact hm⟩, hq]

theorem accepts_idTable (g : CFG) (t : Tree) :
    (g.toTA).accepts idTable t
      = ((g.toTA).evalT idTable t).any fun q => decide (q ∈ g.starts) := by
  simp only [TA.accepts, idTable, List.any_cons, List.any_nil, Bool.or_false]
  rfl

/--
**Theorem A.10** (Correctness of Translation).  For any CFG `g`, the tree automaton
`g.toTA` accepts exactly the complete parse trees of `g`: `L(A_G) = L_G`.
-/
theorem toTA_correct (g : CFG) (t : Tree) : (g.toTA).Lang t ↔ g.isParseTree t = true := by
  rw [TA.lang_iff_accepts (isEpsClosure_idTable g), accepts_idTable]
  simp only [isParseTree, List.any_eq_true, decide_eq_true_eq]
  constructor
  · rintro ⟨q, hq, hf⟩; exact ⟨q, hf, (mem_evalT_iff g t q).mp hq⟩
  · rintro ⟨s, hs, hp⟩; exact ⟨s, (mem_evalT_iff g t s).mpr hp, hs⟩

end CFG

end Greta
